# Generated by Django 5.1 on 2026-02-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(choices=[('अन्य उमेदवार', 'backend'), ('दामोदर पौडेल"बैरागी"', 'frontend'), ('अन्य उमेदवार', 'fullstack')], max_length=200),
        ),
    ]
