# Generated by Django 5.1 on 2026-02-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(choices=[('अन्य उमेद्वार', 'backend'), ('दामोदर पौडेल बैरागी', 'frontend'), ('अन्य उमेद्वार', 'fullstack')], max_length=200),
        ),
    ]
