# Generated by Django 5.1 on 2026-02-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(choices=[('अन्य उमेद्वार', 'अन्य उमेद्वार'), ('दामोदर पौडेल बैरागी', 'दामोदर पौडेल बैरागी'), ('अन्य उमेद्वार', 'अन्य उमेद्वार')], max_length=200),
        ),
    ]
